### ISSUE TITLE
Register new HTTP header in HTTP Field Name Registry

### ISSUE THREAD

**Issue by rdanyliw** [dimmyvi/secure-credential-transfer#18]
Section 8.  It appears that this protocol is trying to register a new HTTP header field (Mailbox-Request-ID).  The IANA registry to do that in is https://www.iana.org/assignments/http-fields/http-fields.xhtml (per draft-ietf-httpbis-semantics).

**Comment by dimmyvi** [comment]
Will submit a request to register "Mailbox-Request-ID" header
