### ISSUE TITLE
Use reserved domains in examples

### ISSUE THREAD

**Issue by rdanyliw** [dimmyvi/secure-credential-transfer#20]
Sections 3, 3.4.1, 6.1.6, 6.5.4, and 7.2 all provide examples using “relayserver.com” and “hotel.com”.  IETF document should only use reserved domain (see RFC6761).  For example, s/relayserver.com/relayserver.example.com/

**Comment by dimmyvi** [comment]
Addressed in PR: https://github.com/dimmyvi/secure-credential-transfer/pull/22
