### ISSUE TITLE
Use HTTPS in examples

### ISSUE THREAD

**Issue by rdanyliw** [dimmyvi/secure-credential-transfer#21]
Section 4 says that “The Relay server API endpoint MUST be accessed over HTTP using an https URI [RFC2818] and SHOULD use the default https port.”  This makes sense.  However, the examples in Sections 3, 3.4, 3.4.1, and 7.2 use http://.

**Comment by dimmyvi** [comment]
Addressing this in https://github.com/dimmyvi/secure-credential-transfer/pull/22
