### ISSUE TITLE
Does/should the DeviceClaim be unique per sender/receiver and mailbox?

### ISSUE THREAD

**Issue by mbratz** [dimmyvi/secure-credential-transfer#31]
Hello team defining this API,
Currently I review this API definition in preparation for an implementation. I have the following question:
Has the [DeviceClaim ](https://dimmyvi.github.io/secure-credential-transfer/draft-secure-credential-transfer.html#section-2-4) to be unique per sender/receiver and mailbox? Or is a sender/receiver allowed to reuse a Device Claim UUID for several mailboxes? 
If it can be reused [Sender/Receiver privacy](https://dimmyvi.github.io/secure-credential-transfer/draft-secure-credential-transfer.html#name-sender-receiver-privacy) might be affected.

Thank you for clarifying, Marco

**Comment by alexpell00** [comment]
Hello! There is nothing on the relay server preventing the sending and receiver from reusing device claim, but as you pointed out they should not. Reusing the device claim across multiple mailboxes would result in the relay server being able to track clients and correlate transfers.
